#!/usr/bin/env perl

use strict;
use warnings qw(all);

use Getopt::Long qw(GetOptions :config no_ignore_case);
use Pod::Usage;
use Cwd 'abs_path';
use File::Basename;

# run PIRATE on annotated assemblies from the NCBI/refseq

=head1  SYNOPSIS

 annotation_to_PIRATE -i /path/to/assembly_summary_refseq.txt -o ./path/to/output_dir/ 

 Input/output:
 -i|--input 	path to assembly_summary_refseq.txt [required]
 -o|--output 	output directory, must contain assemblies [required]
 -p|--pirate	path to pirate executable [required]
 
 General options:	
 -t|--threads	parallel threads [default: 2] 
 -a|--args	arguments for PIRATE [default: none]
 -h|--help 	usage information
 
=cut

# command line options
my $input = '';
my $output_dir = '';
my $parallel = 2;
my $help = 0;
my $args = "";
my $pirate_path = "";

pod2usage(1) if scalar(@ARGV) == 0;
GetOptions(

	'input=s' 	=> \$input,
	'output=s'	=> \$output_dir,
	'threads=i'  => \$parallel,
	'args=s'	=> \$args,
	'pirate=s' => \$pirate_path,
	
	'help|?' 	=> \$help,

) or die pod2usage(1);
pod2usage(1) if $help;

# script path
my $script_path = abs_path(dirname($0));

# check
die " - ERROR: input file not specified\n" if $input eq "";
die " - ERROR: output directory not specified\n" if $output_dir eq "";
die " - ERROR: output directory not specified\n" if $pirate_path eq "";

# check input/output directory
unless( -d $output_dir ){
	die " - ERROR: output directory does not exist\n"; 
}

# parse input file  
my $ftp_idx = 0;
my $idx = 0;
my %sample_hash = ();
my $s_count = 0;
open IN, $input or die " - ERROR: input file did not open\n";
while(<IN>){
	
	# headers
	my $line = $_;
	chomp $line;
	
	my @vars = split("\t", $line, -1);
	
	# headers
	if( (/^# assembly/) || (/^assembly/) ){
		
		my $t = 0;
		for my $i (0..$#vars){
			
			if( ($vars[$i] eq "species_taxid") && ($idx eq "") ){
				$idx = $i;
				$t = 1;
			}elsif($vars[$i] eq "species"){
				$idx = $i;
				$t = 2;
			}
			if( ($vars[$i] eq "ftp_path") ){
				$ftp_idx = $i;
			}
		}
		
		# feedback
		print " - directories named on taxon id\n" if ( $t == 1 ) ;
		print " - directories named on species name\n" if ( $t == 1 ) ;
		die " - species_taxid or species headers not found\n" if $t == 0;
		die " - ftp_path headers not found\n" if $ftp_idx eq "";
		
	}elsif(/^#/){
	# store info per matching isolate
	}else{
	
		++$s_count;
	
		my $acc = $vars[0]; # accession
		my $ftp = $vars[$ftp_idx]; # ftp_path
		my $spp_raw = $vars[$idx]; # name
		
		# remove whitespace
		my $spp = $spp_raw;
		$spp =~ s/\s+/_/g;
		
		$sample_hash{$spp}{$acc} = $ftp;
	}

}close IN;

# feedback
my $no_spp = keys(%sample_hash);
print " - $s_count samples from $no_spp species/taxa\n";

# open output file
open SUM, ">$output_dir/prokka_summary.tab" or die " - ERROR: output summary ($output_dir/prokka_summary.tab) did not open.\n";

# PIRATE species sequentially
my $count = 0;
my @all = ();
print " - 0 species/taxon processed (0 %)        ";
for my $sp (keys %sample_hash){
	
	++$count;
	
	# check files/dirs
	my $output_dir_a = sprintf("%s/%s/", $output_dir, $sp); 
	$output_dir_a =~ s/\/\//\//g;
	die " - $output_dir_a does not exist\n" unless( -d $output_dir_a );
	
	my $output_dir_b = sprintf("%s/annotation/gff/", $output_dir_a); 
	$output_dir_b =~ s/\/\//\//g;
	die " - $output_dir_b does not exist\n" unless( -d $output_dir_b );
	
	# create output dir
	my $output_dir_c = sprintf("%s/pangenome/", $output_dir_a); 
	$output_dir_c =~ s/\/\//\//g;
	unless( -d $output_dir_c ){
		die " - ERROR: could not make $output_dir_c\n" unless mkdir $output_dir_c; 
	}
	
	# run PIRATE
	`$pirate_path -i $output_dir_b -o $output_dir_c -t $parallel $args`;
	die " - ERROR: PIRATE failed on $sp" if $?;
	
      # feedback
	my $per = sprintf( "%.3f", $count/$no_spp * 100) ;
	print "\r - $count species/taxon processed ($per %)          ";

}
print "\n";
close SUM;

exit;
